name: tests se lance sur les pokémons de type dev 

on:
  push:
    branches:
      - 'main'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: todolist_api
        run: npm install
      - name: Test
        working-directory: todolist_api
        run: npm run test
      - name: Send message to Discord
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "deploy success Bitch ! https://tenor.com/view/rosycheeks-approved-i-approve-well-done-good-job-gif-16996150"}' \
          ${{ secrets.DISCORD_MOTHER_FUCKER }}
