name: tests se lance sur les pokémons de type dev 

on:
  push:
    branches:
      - 'dev_*'
      - 'dev'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: todolist_api
        run: npm install
      - name: Build
        working-directory: todolist_api
        run: npm run build
      - name: Test
        working-directory: todolist_api
        run: npm run test
