name: tests se lance sur les pokémons de type dev 

on:
  push:
    branches:
      - 'dev_*'
      - 'dev'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Change directory
        run: cd ./todolist_api
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
